javac -g -classpath ..\lib\perst.jar;. Guess.java
javac -g -classpath ..\lib\perst.jar;. TestIndex.java
javac -g -classpath ..\lib\perst.jar;. TestLink.java
javac -g -classpath ..\lib\perst.jar;. TestGC.java
javac -g -classpath ..\lib\perst.jar;. TestConcur.java
javac -g -classpath ..\lib\perst.jar;. TestRtree.java
javac -g -classpath ..\lib\perst.jar;. TestIndexIterator.java
javac -g -classpath ..\lib\perst.jar;. TestRaw.java
javac -g -classpath ..\lib\perst.jar;. TestXML.java
javac -g -classpath ..\lib\perst.jar;. TestSSD.java
