del *.dbs
call TestIndex
call TestCompoundIndex
call TestMod
call TestIndexIterator
call TestRtree
call TestTtree
call TestRaw
call TestGC
call TestConcur
call TestXML
call TestBlob
call TestBlob
