del *.dbs
call TestIndex
call TestCompoundIndex
call TestMod
call TestIndexIterator
call TestRtree
call TestR2
call TestTtree
call TestRaw
call TestRaw
call TestGC
call TestConcur
call TestXML
call TestBackup
call TestBlob
call TestBlob
call TestTimeSeries
